#!/bin/sh

# additional executions

composer install
cron
/usr/local/bin/php /var/www/vendor/bin/teebot listener:start /var/www/src

# php-fpm

set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"